// <auto-generated />
using System;
using Formula1.Infra.Database.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Formula1.Infra.Migrations
{
    [DbContext(typeof(F1Db))]
    [Migration("20190419133730_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Formula1.Data.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EquipeId");

                    b.Property<int?>("PilotoId");

                    b.Property<int>("Temporada");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("PilotoId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Formula1.Data.Entities.Corrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Circuito");

                    b.Property<DateTime>("DataHoraBrasil");

                    b.Property<string>("NomeGrandePremio");

                    b.Property<int>("Temporada");

                    b.HasKey("Id");

                    b.ToTable("Corridas");
                });

            modelBuilder.Entity("Formula1.Data.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("Formula1.Data.Entities.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<string>("NomeGuerra");

                    b.Property<int>("NumeroCarro");

                    b.Property<string>("PaisOrigem");

                    b.Property<string>("Sigla");

                    b.HasKey("Id");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("Formula1.Data.Entities.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CorridaId");

                    b.Property<bool>("DNF");

                    b.Property<int?>("EquipeId");

                    b.Property<int?>("MotivoDNF");

                    b.Property<int?>("PilotoId");

                    b.Property<int>("Pontos");

                    b.Property<int>("PosicaoChegada");

                    b.Property<int>("PosicaoLargada");

                    b.HasKey("Id");

                    b.HasIndex("CorridaId");

                    b.HasIndex("EquipeId");

                    b.HasIndex("PilotoId");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("Formula1.Data.Entities.Contrato", b =>
                {
                    b.HasOne("Formula1.Data.Entities.Equipe", "Equipe")
                        .WithMany("Contratos")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Formula1.Data.Entities.Piloto", "Piloto")
                        .WithMany("Contratos")
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Formula1.Data.Entities.Resultado", b =>
                {
                    b.HasOne("Formula1.Data.Entities.Corrida", "Corrida")
                        .WithMany("Resultados")
                        .HasForeignKey("CorridaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Formula1.Data.Entities.Equipe", "Equipe")
                        .WithMany("Resultados")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Formula1.Data.Entities.Piloto", "Piloto")
                        .WithMany("Resultados")
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
