// <auto-generated />
using System;
using Formula1.Infra.Database.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Formula1.Infra.Migrations
{
    [DbContext(typeof(F1Db))]
    [Migration("20190421030235_DadosContrato")]
    partial class DadosContrato
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Formula1.Data.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EquipeId");

                    b.Property<int?>("PilotoId");

                    b.Property<int>("Temporada");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.HasIndex("PilotoId");

                    b.HasIndex("Temporada");

                    b.ToTable("Contratos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipeId = 1,
                            PilotoId = 1,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 2,
                            EquipeId = 1,
                            PilotoId = 2,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 3,
                            EquipeId = 2,
                            PilotoId = 3,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 4,
                            EquipeId = 2,
                            PilotoId = 4,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 5,
                            EquipeId = 3,
                            PilotoId = 5,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 6,
                            EquipeId = 3,
                            PilotoId = 6,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 7,
                            EquipeId = 5,
                            PilotoId = 8,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 8,
                            EquipeId = 5,
                            PilotoId = 7,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 9,
                            EquipeId = 8,
                            PilotoId = 17,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 10,
                            EquipeId = 8,
                            PilotoId = 18,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 11,
                            EquipeId = 10,
                            PilotoId = 15,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 12,
                            EquipeId = 10,
                            PilotoId = 16,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 13,
                            EquipeId = 4,
                            PilotoId = 11,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 14,
                            EquipeId = 4,
                            PilotoId = 12,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 15,
                            EquipeId = 7,
                            PilotoId = 13,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 16,
                            EquipeId = 7,
                            PilotoId = 14,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 17,
                            EquipeId = 9,
                            PilotoId = 9,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 18,
                            EquipeId = 9,
                            PilotoId = 10,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 19,
                            EquipeId = 6,
                            PilotoId = 20,
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 20,
                            EquipeId = 6,
                            PilotoId = 19,
                            Temporada = 2019
                        });
                });

            modelBuilder.Entity("Formula1.Data.Entities.Corrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Circuito");

                    b.Property<DateTime>("DataHoraBrasil");

                    b.Property<string>("NomeGrandePremio");

                    b.Property<int>("Temporada");

                    b.HasKey("Id");

                    b.HasIndex("Temporada");

                    b.ToTable("Corridas");

                    b.HasData(
                        new
                        {
                            Id = 998,
                            Circuito = "Circuito de Albert Park",
                            DataHoraBrasil = new DateTime(2019, 3, 17, 2, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Austrália",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 999,
                            Circuito = "Circuito Internacional do Bahrein",
                            DataHoraBrasil = new DateTime(2019, 3, 31, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP do Bahrein",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1000,
                            Circuito = "Circuito Internacional de Xangai",
                            DataHoraBrasil = new DateTime(2019, 4, 14, 3, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da China",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1001,
                            Circuito = "Curcuito Urbano de Baku",
                            DataHoraBrasil = new DateTime(2019, 4, 28, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP do Azerbaijão",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1002,
                            Circuito = "Circuito da Catalunha",
                            DataHoraBrasil = new DateTime(2019, 5, 12, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Espanha",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1003,
                            Circuito = "Circuito de Mônaco",
                            DataHoraBrasil = new DateTime(2019, 5, 26, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP de Mônaco",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1004,
                            Circuito = "Circuito Gilles Villeneuve",
                            DataHoraBrasil = new DateTime(2019, 6, 9, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP do Canadá",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1005,
                            Circuito = "Circuito Paul Ricard",
                            DataHoraBrasil = new DateTime(2019, 6, 23, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da França",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1006,
                            Circuito = "Red Bull Ring",
                            DataHoraBrasil = new DateTime(2019, 6, 30, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Áustria",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1007,
                            Circuito = "Silverstone",
                            DataHoraBrasil = new DateTime(2019, 7, 14, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Grã-Bretanha",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1008,
                            Circuito = "Hockenheimring",
                            DataHoraBrasil = new DateTime(2019, 7, 28, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Alemanha",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1009,
                            Circuito = "Hungaroring",
                            DataHoraBrasil = new DateTime(2019, 8, 4, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Hungria",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1010,
                            Circuito = "Spa-Francorchamps",
                            DataHoraBrasil = new DateTime(2019, 9, 1, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Bélgica",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1011,
                            Circuito = "Circuito de Monza",
                            DataHoraBrasil = new DateTime(2019, 9, 8, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Itália",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1012,
                            Circuito = "Circuito Urbano de Marina Bay",
                            DataHoraBrasil = new DateTime(2019, 9, 22, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP de Singapura",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1013,
                            Circuito = "Autódromo de Sóchi",
                            DataHoraBrasil = new DateTime(2019, 9, 29, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP da Rússia",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1014,
                            Circuito = "Circuito de Suzuka",
                            DataHoraBrasil = new DateTime(2019, 10, 13, 2, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP do Japão",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1015,
                            Circuito = "Autódromo Hermanos Rodríguez",
                            DataHoraBrasil = new DateTime(2019, 10, 27, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP do México",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1016,
                            Circuito = "Circuito das Américas",
                            DataHoraBrasil = new DateTime(2019, 11, 3, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP dos Estados Unidos",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1017,
                            Circuito = "Autódromo José Carlos Pace",
                            DataHoraBrasil = new DateTime(2019, 11, 17, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP do Brasil",
                            Temporada = 2019
                        },
                        new
                        {
                            Id = 1018,
                            Circuito = "Circuito de Yas Marina",
                            DataHoraBrasil = new DateTime(2019, 12, 1, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            NomeGrandePremio = "GP do Abu Dhabi",
                            Temporada = 2019
                        });
                });

            modelBuilder.Entity("Formula1.Data.Entities.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Equipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mercedes"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Ferrari"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "RedBull Racing"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Scuderia Toro Rosso"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Renault"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Williams"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "McLaren"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Racing Point"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Haas"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Alfa Romeo"
                        });
                });

            modelBuilder.Entity("Formula1.Data.Entities.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<string>("NomeGuerra");

                    b.Property<int>("NumeroCarro");

                    b.Property<string>("PaisOrigem");

                    b.Property<string>("Sigla");

                    b.HasKey("Id");

                    b.ToTable("Pilotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Lewis Hamilton",
                            NomeGuerra = "Hamilton",
                            NumeroCarro = 44,
                            PaisOrigem = "Inglaterra",
                            Sigla = "HAM"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Valtteri Bottas",
                            NomeGuerra = "Bottas",
                            NumeroCarro = 77,
                            PaisOrigem = "Finlândia",
                            Sigla = "BOT"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Sebastian Vettel",
                            NomeGuerra = "Vettel",
                            NumeroCarro = 5,
                            PaisOrigem = "Alemanha",
                            Sigla = "VET"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Charles Leclerc",
                            NomeGuerra = "Leclerc",
                            NumeroCarro = 16,
                            PaisOrigem = "Mônaco",
                            Sigla = "LEC"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Max Verstappen",
                            NomeGuerra = "Verstappen",
                            NumeroCarro = 33,
                            PaisOrigem = "Holanda (talvez)",
                            Sigla = "VER"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Pierre Gasly",
                            NomeGuerra = "Gasly",
                            NumeroCarro = 10,
                            PaisOrigem = "França",
                            Sigla = "GAS"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Daniel Riccardo",
                            NomeGuerra = "Riccardo",
                            NumeroCarro = 3,
                            PaisOrigem = "Austrália",
                            Sigla = "RIC"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Nico Hülkenberg",
                            NomeGuerra = "Hülkenberg",
                            NumeroCarro = 27,
                            PaisOrigem = "Alemanha",
                            Sigla = "HUL"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Kevin Magnussen",
                            NomeGuerra = "Magnussen",
                            NumeroCarro = 20,
                            PaisOrigem = "Dinamarca",
                            Sigla = "MAG"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Romain Grosjean",
                            NomeGuerra = "Grosjean",
                            NumeroCarro = 8,
                            PaisOrigem = "França",
                            Sigla = "GRO"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Daniil Kvyat",
                            NomeGuerra = "Kvyat",
                            NumeroCarro = 26,
                            PaisOrigem = "Rússia",
                            Sigla = "KVY"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Alexander Albon",
                            NomeGuerra = "Albon",
                            NumeroCarro = 23,
                            PaisOrigem = "?",
                            Sigla = "ALB"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Lando Norris",
                            NomeGuerra = "Norris",
                            NumeroCarro = 4,
                            PaisOrigem = "Inglaterra",
                            Sigla = "NOR"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Carlos Sainz Jr.",
                            NomeGuerra = "Sainz",
                            NumeroCarro = 55,
                            PaisOrigem = "Espanha",
                            Sigla = "SAI"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Kimi Räikkönen",
                            NomeGuerra = "Räikkönen",
                            NumeroCarro = 7,
                            PaisOrigem = "Finlândia",
                            Sigla = "RAI"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Antonio Giovinazzi",
                            NomeGuerra = "Giovinazzi",
                            NumeroCarro = 99,
                            PaisOrigem = "Itália",
                            Sigla = "GIO"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Sergio Perez",
                            NomeGuerra = "Perez",
                            NumeroCarro = 11,
                            PaisOrigem = "México",
                            Sigla = "PER"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Lance Stroll",
                            NomeGuerra = "Stroll",
                            NumeroCarro = 18,
                            PaisOrigem = "Canadá",
                            Sigla = "STR"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Robert Kubica",
                            NomeGuerra = "Kubica",
                            NumeroCarro = 88,
                            PaisOrigem = "Polônia",
                            Sigla = "KUB"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "George Russell",
                            NomeGuerra = "Russell",
                            NumeroCarro = 63,
                            PaisOrigem = "Inglaterra",
                            Sigla = "RUS"
                        });
                });

            modelBuilder.Entity("Formula1.Data.Entities.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CorridaId");

                    b.Property<bool>("DNF");

                    b.Property<int?>("EquipeId");

                    b.Property<int?>("MotivoDNF");

                    b.Property<int?>("PilotoId");

                    b.Property<bool>("PontoExtra");

                    b.Property<int>("Pontos");

                    b.Property<int>("PosicaoChegada");

                    b.Property<int>("PosicaoLargada");

                    b.HasKey("Id");

                    b.HasIndex("CorridaId");

                    b.HasIndex("EquipeId");

                    b.HasIndex("PilotoId");

                    b.ToTable("Resultados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 1,
                            PilotoId = 2,
                            PontoExtra = true,
                            Pontos = 26,
                            PosicaoChegada = 1,
                            PosicaoLargada = 2
                        },
                        new
                        {
                            Id = 2,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 1,
                            PilotoId = 1,
                            PontoExtra = false,
                            Pontos = 18,
                            PosicaoChegada = 2,
                            PosicaoLargada = 1
                        },
                        new
                        {
                            Id = 3,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 3,
                            PilotoId = 5,
                            PontoExtra = false,
                            Pontos = 15,
                            PosicaoChegada = 3,
                            PosicaoLargada = 4
                        },
                        new
                        {
                            Id = 4,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 2,
                            PilotoId = 3,
                            PontoExtra = false,
                            Pontos = 12,
                            PosicaoChegada = 4,
                            PosicaoLargada = 3
                        },
                        new
                        {
                            Id = 5,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 2,
                            PilotoId = 4,
                            PontoExtra = false,
                            Pontos = 10,
                            PosicaoChegada = 5,
                            PosicaoLargada = 5
                        },
                        new
                        {
                            Id = 6,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 9,
                            PilotoId = 9,
                            PontoExtra = false,
                            Pontos = 8,
                            PosicaoChegada = 6,
                            PosicaoLargada = 7
                        },
                        new
                        {
                            Id = 7,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 5,
                            PilotoId = 8,
                            PontoExtra = false,
                            Pontos = 6,
                            PosicaoChegada = 7,
                            PosicaoLargada = 11
                        },
                        new
                        {
                            Id = 8,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 10,
                            PilotoId = 15,
                            PontoExtra = false,
                            Pontos = 4,
                            PosicaoChegada = 8,
                            PosicaoLargada = 9
                        },
                        new
                        {
                            Id = 9,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 8,
                            PilotoId = 18,
                            PontoExtra = false,
                            Pontos = 2,
                            PosicaoChegada = 9,
                            PosicaoLargada = 16
                        },
                        new
                        {
                            Id = 10,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 4,
                            PilotoId = 11,
                            PontoExtra = false,
                            Pontos = 1,
                            PosicaoChegada = 10,
                            PosicaoLargada = 15
                        },
                        new
                        {
                            Id = 11,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 3,
                            PilotoId = 6,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 11,
                            PosicaoLargada = 17
                        },
                        new
                        {
                            Id = 12,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 7,
                            PilotoId = 13,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 12,
                            PosicaoLargada = 8
                        },
                        new
                        {
                            Id = 13,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 8,
                            PilotoId = 17,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 13,
                            PosicaoLargada = 10
                        },
                        new
                        {
                            Id = 14,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 4,
                            PilotoId = 12,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 14,
                            PosicaoLargada = 13
                        },
                        new
                        {
                            Id = 15,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 10,
                            PilotoId = 16,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 15,
                            PosicaoLargada = 14
                        },
                        new
                        {
                            Id = 16,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 6,
                            PilotoId = 20,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 16,
                            PosicaoLargada = 19
                        },
                        new
                        {
                            Id = 17,
                            CorridaId = 998,
                            DNF = false,
                            EquipeId = 6,
                            PilotoId = 19,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 17,
                            PosicaoLargada = 20
                        },
                        new
                        {
                            Id = 18,
                            CorridaId = 998,
                            DNF = true,
                            EquipeId = 9,
                            MotivoDNF = 1,
                            PilotoId = 10,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 18,
                            PosicaoLargada = 6
                        },
                        new
                        {
                            Id = 19,
                            CorridaId = 998,
                            DNF = true,
                            EquipeId = 5,
                            MotivoDNF = 2,
                            PilotoId = 7,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 19,
                            PosicaoLargada = 12
                        },
                        new
                        {
                            Id = 20,
                            CorridaId = 998,
                            DNF = true,
                            EquipeId = 7,
                            MotivoDNF = 3,
                            PilotoId = 14,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 20,
                            PosicaoLargada = 18
                        },
                        new
                        {
                            Id = 21,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 1,
                            PilotoId = 1,
                            PontoExtra = false,
                            Pontos = 25,
                            PosicaoChegada = 1,
                            PosicaoLargada = 3
                        },
                        new
                        {
                            Id = 22,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 1,
                            PilotoId = 2,
                            PontoExtra = false,
                            Pontos = 18,
                            PosicaoChegada = 2,
                            PosicaoLargada = 4
                        },
                        new
                        {
                            Id = 23,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 2,
                            PilotoId = 4,
                            PontoExtra = true,
                            Pontos = 16,
                            PosicaoChegada = 3,
                            PosicaoLargada = 1
                        },
                        new
                        {
                            Id = 24,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 3,
                            PilotoId = 5,
                            PontoExtra = false,
                            Pontos = 12,
                            PosicaoChegada = 4,
                            PosicaoLargada = 5
                        },
                        new
                        {
                            Id = 25,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 2,
                            PilotoId = 3,
                            PontoExtra = false,
                            Pontos = 10,
                            PosicaoChegada = 5,
                            PosicaoLargada = 2
                        },
                        new
                        {
                            Id = 26,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 7,
                            PilotoId = 13,
                            PontoExtra = false,
                            Pontos = 8,
                            PosicaoChegada = 6,
                            PosicaoLargada = 9
                        },
                        new
                        {
                            Id = 27,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 10,
                            PilotoId = 15,
                            PontoExtra = false,
                            Pontos = 6,
                            PosicaoChegada = 7,
                            PosicaoLargada = 8
                        },
                        new
                        {
                            Id = 28,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 3,
                            PilotoId = 6,
                            PontoExtra = false,
                            Pontos = 4,
                            PosicaoChegada = 8,
                            PosicaoLargada = 13
                        },
                        new
                        {
                            Id = 29,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 4,
                            PilotoId = 12,
                            PontoExtra = false,
                            Pontos = 2,
                            PosicaoChegada = 9,
                            PosicaoLargada = 12
                        },
                        new
                        {
                            Id = 30,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 8,
                            PilotoId = 17,
                            PontoExtra = false,
                            Pontos = 1,
                            PosicaoChegada = 10,
                            PosicaoLargada = 14
                        },
                        new
                        {
                            Id = 31,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 10,
                            PilotoId = 16,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 11,
                            PosicaoLargada = 16
                        },
                        new
                        {
                            Id = 32,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 4,
                            PilotoId = 11,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 12,
                            PosicaoLargada = 15
                        },
                        new
                        {
                            Id = 33,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 9,
                            PilotoId = 9,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 13,
                            PosicaoLargada = 6
                        },
                        new
                        {
                            Id = 34,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 8,
                            PilotoId = 18,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 14,
                            PosicaoLargada = 18
                        },
                        new
                        {
                            Id = 35,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 6,
                            PilotoId = 20,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 15,
                            PosicaoLargada = 19
                        },
                        new
                        {
                            Id = 36,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 6,
                            PilotoId = 19,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 16,
                            PosicaoLargada = 20
                        },
                        new
                        {
                            Id = 37,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 5,
                            PilotoId = 8,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 17,
                            PosicaoLargada = 17
                        },
                        new
                        {
                            Id = 38,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 5,
                            PilotoId = 7,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 18,
                            PosicaoLargada = 10
                        },
                        new
                        {
                            Id = 39,
                            CorridaId = 999,
                            DNF = false,
                            EquipeId = 7,
                            PilotoId = 14,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 19,
                            PosicaoLargada = 7
                        },
                        new
                        {
                            Id = 40,
                            CorridaId = 999,
                            DNF = true,
                            EquipeId = 9,
                            MotivoDNF = 4,
                            PilotoId = 10,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 20,
                            PosicaoLargada = 11
                        },
                        new
                        {
                            Id = 41,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 1,
                            PilotoId = 1,
                            PontoExtra = false,
                            Pontos = 25,
                            PosicaoChegada = 1,
                            PosicaoLargada = 2
                        },
                        new
                        {
                            Id = 42,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 1,
                            PilotoId = 2,
                            PontoExtra = false,
                            Pontos = 18,
                            PosicaoChegada = 2,
                            PosicaoLargada = 1
                        },
                        new
                        {
                            Id = 43,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 2,
                            PilotoId = 3,
                            PontoExtra = false,
                            Pontos = 15,
                            PosicaoChegada = 3,
                            PosicaoLargada = 3
                        },
                        new
                        {
                            Id = 44,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 3,
                            PilotoId = 5,
                            PontoExtra = false,
                            Pontos = 12,
                            PosicaoChegada = 4,
                            PosicaoLargada = 5
                        },
                        new
                        {
                            Id = 45,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 2,
                            PilotoId = 4,
                            PontoExtra = false,
                            Pontos = 10,
                            PosicaoChegada = 5,
                            PosicaoLargada = 4
                        },
                        new
                        {
                            Id = 46,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 3,
                            PilotoId = 6,
                            PontoExtra = true,
                            Pontos = 9,
                            PosicaoChegada = 6,
                            PosicaoLargada = 6
                        },
                        new
                        {
                            Id = 47,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 5,
                            PilotoId = 7,
                            PontoExtra = false,
                            Pontos = 6,
                            PosicaoChegada = 7,
                            PosicaoLargada = 7
                        },
                        new
                        {
                            Id = 48,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 8,
                            PilotoId = 17,
                            PontoExtra = false,
                            Pontos = 4,
                            PosicaoChegada = 8,
                            PosicaoLargada = 12
                        },
                        new
                        {
                            Id = 49,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 10,
                            PilotoId = 15,
                            PontoExtra = false,
                            Pontos = 2,
                            PosicaoChegada = 9,
                            PosicaoLargada = 13
                        },
                        new
                        {
                            Id = 50,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 4,
                            PilotoId = 12,
                            PontoExtra = false,
                            Pontos = 1,
                            PosicaoChegada = 10,
                            PosicaoLargada = 20
                        },
                        new
                        {
                            Id = 51,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 9,
                            PilotoId = 10,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 11,
                            PosicaoLargada = 10
                        },
                        new
                        {
                            Id = 52,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 8,
                            PilotoId = 18,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 12,
                            PosicaoLargada = 16
                        },
                        new
                        {
                            Id = 53,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 9,
                            PilotoId = 9,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 13,
                            PosicaoLargada = 9
                        },
                        new
                        {
                            Id = 54,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 7,
                            PilotoId = 14,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 14,
                            PosicaoLargada = 14
                        },
                        new
                        {
                            Id = 55,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 10,
                            PilotoId = 16,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 15,
                            PosicaoLargada = 19
                        },
                        new
                        {
                            Id = 56,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 6,
                            PilotoId = 20,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 16,
                            PosicaoLargada = 17
                        },
                        new
                        {
                            Id = 57,
                            CorridaId = 1000,
                            DNF = false,
                            EquipeId = 6,
                            PilotoId = 19,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 17,
                            PosicaoLargada = 18
                        },
                        new
                        {
                            Id = 58,
                            CorridaId = 1000,
                            DNF = true,
                            EquipeId = 7,
                            MotivoDNF = 4,
                            PilotoId = 13,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 18,
                            PosicaoLargada = 15
                        },
                        new
                        {
                            Id = 59,
                            CorridaId = 1000,
                            DNF = true,
                            EquipeId = 4,
                            MotivoDNF = 4,
                            PilotoId = 11,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 19,
                            PosicaoLargada = 11
                        },
                        new
                        {
                            Id = 60,
                            CorridaId = 1000,
                            DNF = true,
                            EquipeId = 5,
                            MotivoDNF = 3,
                            PilotoId = 8,
                            PontoExtra = false,
                            Pontos = 0,
                            PosicaoChegada = 20,
                            PosicaoLargada = 8
                        });
                });

            modelBuilder.Entity("Formula1.Data.Entities.Contrato", b =>
                {
                    b.HasOne("Formula1.Data.Entities.Equipe", "Equipe")
                        .WithMany("Contratos")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Formula1.Data.Entities.Piloto", "Piloto")
                        .WithMany("Contratos")
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Formula1.Data.Entities.Resultado", b =>
                {
                    b.HasOne("Formula1.Data.Entities.Corrida", "Corrida")
                        .WithMany("Resultados")
                        .HasForeignKey("CorridaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Formula1.Data.Entities.Equipe", "Equipe")
                        .WithMany("Resultados")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Formula1.Data.Entities.Piloto", "Piloto")
                        .WithMany("Resultados")
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
