name: Publicar no Servidor Linux via SSH

on:
  push:
    branches:
      ['master']

jobs:
  build:
    name: 'Build da aplicação'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar o .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restaurar pacotes
        run: dotnet restore

      - name: Publicar aplicação
        run: dotnet publish -c Release -o ./publish -r linux-x64

      - uses: actions/upload-artifact@v4
        with:
          name: pub-artifact
          path: ./publish

  upload:
    needs: [build]
    name: 'Envio para Servidor Linux'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pub-artifact
          path: ./publish

      - name: Manda pro servidor via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_NAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS_PHRASE }}
          port: ${{ vars.SERVER_PORT }}
          source: ./publish/*
          target: ${{ vars.SERVER_PATH }}
          strip_components: 1 # Remove um nível do folder (publish)
